# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MyNews' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'Alamofire' # 网络请求框架,类似OC的AFNetworking
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'MJRefresh' #刷新
    pod 'SGPagingView' # 模仿美团、头条顶部切换视图
    pod 'IBAnimatable'  # 动态按钮IB
    pod 'SwiftyJSON' # 解析网络数据的jsonstring
    pod 'HandyJSON' # 解析MODEL
    pod 'SVProgressHUD' # HUD
    pod 'BMPlayer', '~> 1.0.1' #播放器
    pod 'Kingfisher' # 图片缓存框架,类似OC的SDWebImage
    pod 'SQLite.swift' # 数据库
    pod 'FDFullscreenPopGesture' # 一个丝滑的全屏滑动返回手势
    pod 'lottie-ios' # 动画库

    #限定库的swift版本
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if ['RxCocoa', 'IBAnimatable', 'BMPlayer', 'NVActivityIndicatorView'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end
    
end
