# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'News' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'IBAnimatable'
  pod 'SwiftTheme'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SQLite.swift'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'SGPagingView'
  pod 'BMPlayer'
  pod 'FDFullscreenPopGesture'
  # pod 'Texture'
  pod 'lottie-ios'
  
  #限定库的swift版本
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if ['RxCocoa', 'SwiftTheme'].include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.0'
              end
          end
      end
  end

end
